title: Riding Rails
url: https://weblog.rubyonrails.org
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - CNAME
permalink: "/:year/:i_month/:i_day/:title/"
markdown: kramdown
category_dir: ""
category_title_prefix: ""
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
feed:
  path: feed/atom.xml
defaults:
  - scope:
      path: ""
    values:
      image: https://avatars.githubusercontent.com/u/4223
